language: android

jdk:
  - openjdk11

android:
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.3

    # The SDK version used to compile your project
    - android-19

branches:
  only:
    - master

script:
  - $HOME/gradlew build

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    tags: true
